name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: test echo
      run: echo Hi Mars...!
    - name: gcc version
      run: g++ --version
    - name: compile and run gcc
      run: |
        g++ main.cpp play01Templates.cpp playground.cpp
        .\a.out
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
