name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: test echo
      run: echo Hi Mars...!
    - name: gcc version
      run: g++ --version
    - name: Check if cppcheck is installed
      run: |
        if ! command -v cppcheck &> /dev/null; then
          echo "cppcheck not found, installing..."
          sudo apt-get install cppcheck -y
        else
          echo "cppcheck is already installed."
        fi
    - name: cppcheck version
      run: cppcheck --version
    - name: ls
      run: ls
    - name: compile and run gcc make
      run: |
          make
          ls
          ./build/bin/myprogram
    - name: Run Unit Test
      run: |
        sudo apt install libgtest-dev cmake
        cd ../lib/googletest/
        mkdir lib/googletest/build
        rm -r  build
        mkdir build
        cmake ..
        make
        cd ../../../
        cd test
        make clean
        mkdir build
        ./test_main
        cd ../
    - name: make cppcheck
      run: make cppcheck
    - name: make clean
      run: make
